"""
pilates_logic.py — The Pilates Flow Brain
Comprehensive exercise database (~180 exercises), bell-curve generator, and smart-swap logic.
All exercises are real, recognized Pilates repertoire across Reformer, Mat, Chair,
Cadillac/Tower, Ladder Barrel, and Spine Corrector.
"""

import random
import json
from dataclasses import dataclass, field, asdict
from typing import Optional

# ─────────────────────────────────────────────
# Data Models
# ─────────────────────────────────────────────

@dataclass
class Exercise:
    slug: str
    name: str
    apparatus: str          # "Reformer", "Mat", "Chair", "Cadillac", "Ladder Barrel", "Spine Corrector"
    category: str           # e.g. "Supine Abdominals", "Hip Work", "Arm Work"
    phase: str              # "warmup", "foundation", "peak", "cooldown"
    energy: int             # 1-5 intensity scale
    default_springs: str    # e.g. "2 Red" or "N/A" for mat
    duration_min: float     # typical minutes
    cues: list[str] = field(default_factory=list)
    themes: list[str] = field(default_factory=list)  # "Core", "Flexibility", etc.
    image: str = ""         # filename in /assets
    level: str = "all"      # "beginner", "intermediate", "advanced", "all"

    def to_dict(self):
        return asdict(self)


# ─────────────────────────────────────────────
# Exercise Library
# ─────────────────────────────────────────────

EXERCISE_DB: list[Exercise] = [

    # ═══════════════════════════════════════════════════════════════
    #  REFORMER — ~55 exercises
    # ═══════════════════════════════════════════════════════════════

    # --- Reformer: Warmup (14) ---
    Exercise("ref_footwork_parallel", "Footwork – Parallel", "Reformer", "Footwork",
             "warmup", 1, "3 Red + 1 Blue", 3.0,
             ["Heels together, toes apart", "Press evenly through all 10 toes",
              "Keep pelvis neutral – no tucking"],
             ["Core", "Lower Body", "Full Body"], level="beginner"),
    Exercise("ref_footwork_v", "Footwork – V Position", "Reformer", "Footwork",
             "warmup", 1, "3 Red + 1 Blue", 2.0,
             ["Small V with heels touching", "Wrap outer hips",
              "Lengthen through the crown of the head"],
             ["Core", "Lower Body"], level="beginner"),
    Exercise("ref_footwork_wide", "Footwork – Wide Second", "Reformer", "Footwork",
             "warmup", 2, "3 Red + 1 Blue", 2.0,
             ["Wider than hip-width on the bar", "Track knees over second toe",
              "Engage inner thighs on return"],
             ["Lower Body", "Full Body"], level="beginner"),
    Exercise("ref_footwork_heels", "Footwork – Heels", "Reformer", "Footwork",
             "warmup", 1, "3 Red + 1 Blue", 2.0,
             ["Flex feet, heels on bar", "Dorsiflex ankles throughout",
              "Feel hamstring connection"],
             ["Lower Body", "Full Body"], level="beginner"),
    Exercise("ref_footwork_toes", "Footwork – Toes / Pilates V", "Reformer", "Footwork",
             "warmup", 1, "3 Red + 1 Blue", 2.0,
             ["Balls of feet on bar", "Lift heels high",
              "Maintain even pressure across all toes"],
             ["Lower Body", "Balance"], level="beginner"),
    Exercise("ref_footwork_prances", "Footwork – Prances", "Reformer", "Footwork",
             "warmup", 2, "3 Red + 1 Blue", 2.0,
             ["Alternate pressing heels under bar", "Keep carriage still",
              "Feel calf stretch with each press"],
             ["Lower Body", "Flexibility"], level="beginner"),
    Exercise("ref_footwork_single_leg", "Footwork – Single Leg", "Reformer", "Footwork",
             "warmup", 2, "2 Red + 1 Blue", 3.0,
             ["One foot on bar, other in tabletop", "Keep pelvis level",
              "Focus on alignment of working knee"],
             ["Lower Body", "Balance", "Core"], level="intermediate"),
    Exercise("ref_supine_arms_biceps", "Supine Arms – Bicep Curls", "Reformer", "Supine Arm Work",
             "warmup", 1, "1 Red", 2.0,
             ["Arms long by sides holding straps", "Curl hands toward shoulders",
              "Keep elbows pinned to mat"],
             ["Upper Body", "Full Body"], level="beginner"),
    Exercise("ref_supine_arms_triceps", "Supine Arms – Tricep Press", "Reformer", "Supine Arm Work",
             "warmup", 1, "1 Red", 2.0,
             ["Arms at 90 degrees, elbows bent", "Press straps to ceiling",
              "Keep shoulder blades anchored"],
             ["Upper Body", "Full Body"], level="beginner"),
    Exercise("ref_supine_arms_circles", "Supine Arms – Arm Circles", "Reformer", "Supine Arm Work",
             "warmup", 2, "1 Red", 2.0,
             ["Circle arms from hips overhead and back", "Keep ribs heavy",
              "Reverse direction after 5 reps"],
             ["Upper Body", "Flexibility"], level="beginner"),
    Exercise("ref_hundred", "Hundred", "Reformer", "Supine Abdominals",
             "warmup", 3, "1 Red", 4.0,
             ["Curl head and shoulders up", "Pump arms vigorously",
              "Inhale for 5, exhale for 5"],
             ["Core", "Full Body"], level="beginner"),
    Exercise("ref_bridging", "Bridging", "Reformer", "Supine Hip Work",
             "warmup", 2, "2 Red", 3.0,
             ["Feet on bar, arms by sides", "Peel spine up vertebra by vertebra",
              "Press evenly through both feet"],
             ["Core", "Lower Body", "Full Body"], level="beginner"),
    Exercise("ref_roll_down", "Roll Down", "Reformer", "Seated Flexion",
             "warmup", 2, "1 Red", 3.0,
             ["Sit tall facing straps", "Roll down through spine one vertebra at a time",
              "Use abs to control the descent"],
             ["Core", "Flexibility"], level="beginner"),
    Exercise("ref_seated_footwork", "Seated Footwork", "Reformer", "Footwork",
             "warmup", 2, "1 Red + 1 Blue", 3.0,
             ["Sit on carriage facing footbar", "Press out through balls of feet",
              "Maintain tall spine throughout"],
             ["Lower Body", "Core"], level="beginner"),

    # --- Reformer: Foundation (20) ---
    Exercise("ref_feet_straps_circles", "Feet in Straps – Circles", "Reformer", "Supine Hip Work",
             "foundation", 2, "2 Red", 3.0,
             ["Legs in straps, circle from hips", "Keep pelvis stable",
              "Reverse direction after 5-8 reps"],
             ["Lower Body", "Flexibility", "Core"], level="beginner"),
    Exercise("ref_feet_straps_frog", "Feet in Straps – Frog", "Reformer", "Supine Hip Work",
             "foundation", 2, "2 Red", 3.0,
             ["Heels together, toes apart in straps", "Press legs long on diagonal",
              "Draw legs back with control"],
             ["Lower Body", "Core"], level="beginner"),
    Exercise("ref_feet_straps_lower_lift", "Feet in Straps – Lower / Lift", "Reformer", "Supine Hip Work",
             "foundation", 2, "2 Red", 3.0,
             ["Legs to ceiling in straps", "Lower legs as far as back stays stable",
              "Lift back up with inner thigh connection"],
             ["Lower Body", "Core"], level="beginner"),
    Exercise("ref_feet_straps_openings", "Feet in Straps – Openings", "Reformer", "Supine Hip Work",
             "foundation", 2, "2 Red", 3.0,
             ["Legs to ceiling, open to V", "Control the width of the opening",
              "Squeeze inner thighs to close"],
             ["Lower Body", "Flexibility"], level="beginner"),
    Exercise("ref_short_spine", "Short Spine Massage", "Reformer", "Supine Hip Work",
             "foundation", 2, "2 Red", 4.0,
             ["Legs in straps, carriage comes in", "Roll hips over shoulders",
              "Peel down one vertebra at a time"],
             ["Flexibility", "Core", "Full Body"], level="intermediate"),
    Exercise("ref_coordination", "Coordination", "Reformer", "Supine Abdominals",
             "foundation", 3, "1 Red", 3.0,
             ["Curl up, extend arms and legs simultaneously", "Open-close legs",
              "Bend knees in, then lower head — precise timing"],
             ["Core", "Full Body"], level="intermediate"),
    Exercise("ref_stomach_massage_round", "Stomach Massage – Round Back", "Reformer", "Seated Flexion",
             "foundation", 3, "2 Red + 1 Blue", 3.0,
             ["Sit on front edge, feet on bar", "Deep C-curve with round back",
              "Press out and in, deepen scoop each time"],
             ["Core", "Lower Body"], level="intermediate"),
    Exercise("ref_stomach_massage_flat", "Stomach Massage – Hands Back", "Reformer", "Seated Flexion",
             "foundation", 3, "1 Red + 1 Blue", 3.0,
             ["Hands on shoulder rests behind", "Lift chest, open shoulders",
              "Same leg action, tall spine"],
             ["Core", "Upper Body", "Flexibility"], level="intermediate"),
    Exercise("ref_stomach_massage_reach", "Stomach Massage – Reach", "Reformer", "Seated Flexion",
             "foundation", 3, "1 Red", 3.0,
             ["Arms reach forward, no hands for support", "Maintain tall spine",
              "Challenge balance while pressing out"],
             ["Core", "Balance"], level="intermediate"),
    Exercise("ref_stomach_massage_twist", "Stomach Massage – Twist", "Reformer", "Seated Flexion",
             "foundation", 3, "1 Red", 3.0,
             ["Rotate torso as legs press out", "Reach one arm to ceiling",
              "Alternate sides with each press"],
             ["Core", "Flexibility"], level="intermediate"),
    Exercise("ref_short_box_round", "Short Box – Round Back", "Reformer", "Seated Flexion",
             "foundation", 3, "N/A (box)", 3.0,
             ["Sit on box, feet under strap", "Round back, roll halfway down",
              "Use deep abs to pull back up"],
             ["Core", "Flexibility"], level="intermediate"),
    Exercise("ref_short_box_flat", "Short Box – Flat Back", "Reformer", "Seated Flexion",
             "foundation", 3, "N/A (box)", 3.0,
             ["Hinge back with straight spine", "Arms overhead or crossed",
              "Keep length through entire torso"],
             ["Core", "Full Body"], level="intermediate"),
    Exercise("ref_short_box_side", "Short Box – Side Bend", "Reformer", "Lateral Flexion",
             "foundation", 3, "N/A (box)", 3.0,
             ["Side bend over edge of box", "Reach arm overhead",
              "Lift back up using obliques"],
             ["Core", "Flexibility"], level="intermediate"),
    Exercise("ref_short_box_twist", "Short Box – Twist and Reach", "Reformer", "Seated Flexion",
             "foundation", 3, "N/A (box)", 3.0,
             ["Rotate torso, then hinge back on diagonal", "Return to center",
              "Alternate sides"],
             ["Core", "Flexibility"], level="intermediate"),
    Exercise("ref_short_box_tree", "Short Box – Tree", "Reformer", "Seated Flexion",
             "foundation", 2, "N/A (box)", 3.0,
             ["Extend one leg, walk hands up the leg", "Roll down holding leg",
              "Walk hands back up to sit tall"],
             ["Flexibility", "Core"], level="intermediate"),
    Exercise("ref_elephant", "Elephant", "Reformer", "Standing Stretch",
             "foundation", 3, "2 Red + 1 Blue", 3.0,
             ["Stand on carriage, hands on bar", "Round spine like angry cat",
              "Push carriage back with legs, pull in with abs"],
             ["Core", "Flexibility", "Lower Body"], level="intermediate"),
    Exercise("ref_knee_stretch_round", "Knee Stretch – Round Back", "Reformer", "Kneeling Core",
             "foundation", 3, "2 Red", 3.0,
             ["Kneel on carriage, hands on bar", "Deep C-curve in spine",
              "Push carriage back and pull in with abs"],
             ["Core", "Full Body"], level="intermediate"),
    Exercise("ref_knee_stretch_flat", "Knee Stretch – Arched Back", "Reformer", "Kneeling Core",
             "foundation", 3, "2 Red", 3.0,
             ["Same position, extend spine", "Chest lifted, shoulders down",
              "Same push-pull action from abs"],
             ["Core", "Full Body"], level="intermediate"),
    Exercise("ref_scooter", "Scooter", "Reformer", "Standing Hip Work",
             "foundation", 3, "1 Red + 1 Blue", 3.0,
             ["One foot on carriage, one on platform", "Press carriage back with standing leg",
              "Keep hips level and square"],
             ["Lower Body", "Balance", "Core"], level="beginner"),
    Exercise("ref_mermaid", "Mermaid", "Reformer", "Lateral Flexion",
             "foundation", 2, "1 Red", 3.0,
             ["Sit sideways, hand on bar", "Side bend over the bar",
              "Create length on both sides of waist"],
             ["Flexibility", "Core"], level="intermediate"),

    # --- Reformer: Peak (14) ---
    Exercise("ref_long_stretch", "Long Stretch", "Reformer", "Plank / Full Body",
             "peak", 4, "1 Red + 1 Blue", 3.0,
             ["Plank position, hands on bar, feet on shoulder rests",
              "Push carriage back maintaining plank",
              "Pull back in using core — no sagging"],
             ["Core", "Upper Body", "Full Body"], level="intermediate"),
    Exercise("ref_down_stretch", "Down Stretch", "Reformer", "Prone Back Extension",
             "peak", 4, "1 Red + 1 Blue", 3.0,
             ["Kneel on carriage, hands on bar", "Press hips forward, arch back",
              "Pull carriage in lifting chest to ceiling"],
             ["Core", "Flexibility", "Upper Body"], level="intermediate"),
    Exercise("ref_up_stretch", "Up Stretch", "Reformer", "Plank / Full Body",
             "peak", 4, "1 Red + 1 Blue", 3.0,
             ["Pike position on carriage", "Push carriage back in pike",
              "Shift forward to plank, then pike back up"],
             ["Core", "Upper Body", "Full Body"], level="intermediate"),
    Exercise("ref_long_back_stretch", "Long Back Stretch", "Reformer", "Plank / Full Body",
             "peak", 5, "1 Red + 1 Blue", 3.0,
             ["Sit on bar facing shoulder rests, hands on bar", "Press out to reverse plank",
              "Dip hips and lift back up"],
             ["Core", "Upper Body", "Full Body"], level="advanced"),
    Exercise("ref_tendon_stretch", "Tendon Stretch", "Reformer", "Standing Core",
             "peak", 5, "1 Red", 3.0,
             ["Stand on carriage, hands on bar", "Round over, push carriage back with feet",
              "Pull back in with deep scoop"],
             ["Core", "Full Body"], level="advanced"),
    Exercise("ref_semi_circle", "Semi-Circle", "Reformer", "Supine Hip Work",
             "peak", 3, "1 Red", 4.0,
             ["Lie supine with feet on bar, hips off carriage",
              "Drop hips, press out, roll up, pull in",
              "Reverse: roll down, press out, lift up, pull in"],
             ["Flexibility", "Core", "Lower Body"], level="advanced"),
    Exercise("ref_long_spine", "Long Spine Massage", "Reformer", "Supine Hip Work",
             "peak", 3, "2 Red", 4.0,
             ["Legs in straps, press out long", "Roll spine up to shoulder stand",
              "Open legs, roll down with control"],
             ["Flexibility", "Core"], level="intermediate"),
    Exercise("ref_pulling_straps", "Pulling Straps", "Reformer", "Prone Back Extension",
             "peak", 3, "1 Red", 3.0,
             ["Lie prone on long box", "Pull straps alongside body, lift chest",
              "Squeeze shoulder blades together"],
             ["Upper Body", "Core"], level="intermediate"),
    Exercise("ref_pulling_straps_t", "Pulling Straps – T", "Reformer", "Prone Back Extension",
             "peak", 3, "1 Red", 3.0,
             ["Lie prone on long box, arms out to T", "Lift chest and pull arms back",
              "Keep neck long, gaze down"],
             ["Upper Body", "Core"], level="intermediate"),
    Exercise("ref_backstroke", "Backstroke", "Reformer", "Supine Abdominals",
             "peak", 4, "1 Red", 3.0,
             ["Lie supine on box, hold straps", "Arms and legs reach up, then open",
              "Circle arms and legs around, scoop to return"],
             ["Core", "Full Body"], level="advanced"),
    Exercise("ref_teaser", "Teaser", "Reformer", "Supine Abdominals",
             "peak", 4, "1 Red", 3.0,
             ["Lie on box or carriage", "Roll up to V-sit pulling straps",
              "Hold balance, then roll down with control"],
             ["Core", "Balance"], level="advanced"),
    Exercise("ref_breaststroke", "Breaststroke", "Reformer", "Prone Back Extension",
             "peak", 4, "1 Red", 3.0,
             ["Lie prone on box, hold straps", "Extend arms forward, then sweep wide",
              "Lift chest as arms circle back"],
             ["Upper Body", "Core"], level="advanced"),
    Exercise("ref_kneeling_arm_front", "Kneeling Arms – Facing Front", "Reformer", "Kneeling Arm Work",
             "peak", 3, "1 Red", 3.0,
             ["Kneel facing footbar, hold straps", "Press arms down alongside body",
              "Keep torso completely still"],
             ["Upper Body", "Core"], level="intermediate"),
    Exercise("ref_kneeling_arm_back", "Kneeling Arms – Facing Back", "Reformer", "Kneeling Arm Work",
             "peak", 3, "1 Red", 3.0,
             ["Kneel facing shoulder rests, hold straps", "Curl arms or press overhead",
              "Challenge core stability throughout"],
             ["Upper Body", "Core"], level="intermediate"),

    # --- Reformer: Cooldown (8) ---
    Exercise("ref_running", "Running", "Reformer", "Footwork",
             "cooldown", 1, "2 Red", 3.0,
             ["Balls of feet on bar, legs extended", "Alternate bending one knee, lower heel",
              "Like running in place — smooth and rhythmic"],
             ["Lower Body", "Flexibility", "Full Body"], level="beginner"),
    Exercise("ref_pelvic_lift", "Pelvic Lift", "Reformer", "Supine Hip Work",
             "cooldown", 1, "2 Red", 3.0,
             ["Feet on bar in small V, lift hips", "Press out and in while bridge is held",
              "Slowly roll down to finish"],
             ["Lower Body", "Core"], level="beginner"),
    Exercise("ref_eves_lunge", "Eve's Lunge", "Reformer", "Standing Stretch",
             "cooldown", 1, "1 Red", 3.0,
             ["One foot on carriage, one on platform", "Sink into deep lunge",
              "Feel hip flexor and quad stretch"],
             ["Flexibility", "Lower Body", "Balance"], level="beginner"),
    Exercise("ref_side_splits", "Side Splits", "Reformer", "Standing Hip Work",
             "cooldown", 2, "1 Red", 3.0,
             ["Stand with one foot on carriage, one on platform",
              "Press carriage out to straddle",
              "Draw legs together using inner thighs"],
             ["Lower Body", "Balance", "Flexibility"], level="intermediate"),
    Exercise("ref_front_splits", "Front Splits", "Reformer", "Standing Hip Work",
             "cooldown", 3, "1 Red + 1 Blue", 3.0,
             ["One foot on bar, back foot against shoulder rest",
              "Press carriage back into split",
              "Pull back in with hamstring of front leg"],
             ["Flexibility", "Lower Body", "Balance"], level="intermediate"),
    Exercise("ref_russian_splits", "Russian Splits", "Reformer", "Standing Hip Work",
             "cooldown", 4, "1 Red", 3.0,
             ["Stand on carriage facing side, one foot on platform",
              "Press carriage away while lunging",
              "Advanced balance and flexibility challenge"],
             ["Flexibility", "Lower Body", "Balance"], level="advanced"),
    Exercise("ref_standing_hip_stretch", "Standing Hip Stretch", "Reformer", "Standing Stretch",
             "cooldown", 1, "1 Red", 3.0,
             ["Step one foot on carriage, other on platform",
              "Press carriage back gently for hip opener",
              "Hold and breathe into the stretch"],
             ["Flexibility", "Lower Body"], level="beginner"),
    Exercise("ref_mermaid_stretch", "Mermaid Stretch", "Reformer", "Lateral Flexion",
             "cooldown", 1, "1 Red", 3.0,
             ["Sit sideways on carriage", "Reach arm overhead to side bend",
              "Breathe into the stretch, alternate sides"],
             ["Flexibility", "Core"], level="beginner"),

    # ═══════════════════════════════════════════════════════════════
    #  MAT — ~55 exercises
    # ═══════════════════════════════════════════════════════════════

    # --- Mat: Warmup (14) ---
    Exercise("mat_pelvic_clock", "Pelvic Clocks", "Mat", "Supine Core",
             "warmup", 1, "N/A", 3.0,
             ["Lie supine, knees bent", "Gently rock pelvis through clock positions",
              "Find neutral pelvis — not tucked, not arched"],
             ["Core", "Flexibility"], level="beginner"),
    Exercise("mat_chest_lift", "Chest Lift", "Mat", "Supine Abdominals",
             "warmup", 2, "N/A", 3.0,
             ["Hands behind head, elbows wide", "Curl head and chest up on exhale",
              "Keep lower back imprinted"],
             ["Core", "Full Body"], level="beginner"),
    Exercise("mat_leg_slides", "Leg Slides", "Mat", "Supine Core",
             "warmup", 1, "N/A", 2.0,
             ["Lie supine, knees bent", "Slide one leg long along mat",
              "Keep pelvis completely still"],
             ["Core", "Lower Body"], level="beginner"),
    Exercise("mat_knee_folds", "Knee Folds", "Mat", "Supine Core",
             "warmup", 1, "N/A", 2.0,
             ["Lie supine in neutral", "Float one knee to tabletop",
              "Maintain pelvis stability — no rocking"],
             ["Core", "Lower Body"], level="beginner"),
    Exercise("mat_dead_bugs", "Dead Bugs", "Mat", "Supine Core",
             "warmup", 2, "N/A", 3.0,
             ["Both legs in tabletop, arms to ceiling", "Extend opposite arm and leg",
              "Keep lower back connected to mat"],
             ["Core", "Full Body"], level="beginner"),
    Exercise("mat_bridging", "Bridging", "Mat", "Supine Hip Work",
             "warmup", 2, "N/A", 3.0,
             ["Feet flat, hip-width apart", "Peel spine up from tailbone",
              "Roll down one vertebra at a time"],
             ["Core", "Lower Body", "Full Body"], level="beginner"),
    Exercise("mat_cat_cow", "Cat and Cow", "Mat", "Quadruped",
             "warmup", 1, "N/A", 2.0,
             ["On hands and knees", "Round spine up like a cat on exhale",
              "Arch and extend on inhale"],
             ["Flexibility", "Core"], level="beginner"),
    Exercise("mat_arm_arcs", "Arm Arcs", "Mat", "Supine Arm Work",
             "warmup", 1, "N/A", 2.0,
             ["Lie supine, arms to ceiling", "Float arms overhead toward floor",
              "Keep ribs anchored — don't arch"],
             ["Upper Body", "Flexibility"], level="beginner"),
    Exercise("mat_knee_hover", "Knee Hover", "Mat", "Quadruped",
             "warmup", 2, "N/A", 2.0,
             ["On hands and knees", "Hover knees 1 inch off mat",
              "Hold 5-10 breaths, keep spine neutral"],
             ["Core", "Full Body"], level="beginner"),
    Exercise("mat_bent_knee_opening", "Bent Knee Opening", "Mat", "Supine Hip Work",
             "warmup", 1, "N/A", 2.0,
             ["Lie supine, knees bent together", "Let one knee fall open to side",
              "Keep pelvis still, inner thigh controls return"],
             ["Flexibility", "Lower Body"], level="beginner"),
    Exercise("mat_hundred", "Hundred", "Mat", "Supine Abdominals",
             "warmup", 3, "N/A", 4.0,
             ["Curl up, legs extended or in tabletop", "Pump arms vigorously",
              "Inhale 5, exhale 5 — 10 sets"],
             ["Core", "Full Body"], level="beginner"),
    Exercise("mat_book_opening", "Book Opening", "Mat", "Side-Lying Rotation",
             "warmup", 1, "N/A", 2.0,
             ["Side-lying with arms stacked in front", "Open top arm to the sky like a book",
              "Follow hand with your gaze, return"],
             ["Flexibility", "Upper Body"], level="beginner"),
    Exercise("mat_standing_posture", "Standing Posture Check", "Mat", "Standing",
             "warmup", 1, "N/A", 2.0,
             ["Stand tall, feet hip-width", "Stack head over ribs over hips over ankles",
              "Breathe into the side ribs"],
             ["Balance", "Full Body"], level="beginner"),
    Exercise("mat_opposite_arm_leg", "Opposite Arm and Leg Reach", "Mat", "Quadruped",
             "warmup", 2, "N/A", 3.0,
             ["On hands and knees", "Extend right arm and left leg",
              "Keep hips and shoulders level"],
             ["Core", "Balance"], level="beginner"),

    # --- Mat: Foundation (20) ---
    Exercise("mat_roll_up", "Roll Up", "Mat", "Supine Abdominals",
             "foundation", 3, "N/A", 3.0,
             ["Lie flat, arms overhead", "Articulate up one vertebra at a time",
              "Reach past toes, then roll down with control"],
             ["Core", "Flexibility"], level="intermediate"),
    Exercise("mat_rolling_like_ball", "Rolling Like a Ball", "Mat", "Seated Flexion",
             "foundation", 2, "N/A", 3.0,
             ["Balance on sit bones, knees to chest", "Roll back to shoulder blades",
              "Roll back up to balance — use abs not momentum"],
             ["Core", "Balance"], level="intermediate"),
    Exercise("mat_single_leg_stretch", "Single Leg Stretch", "Mat", "Supine Abdominals",
             "foundation", 3, "N/A", 3.0,
             ["Curl up, one knee in to chest", "Switch legs rhythmically",
              "Outside hand to ankle, inside hand to knee"],
             ["Core", "Full Body"], level="intermediate"),
    Exercise("mat_double_leg_stretch", "Double Leg Stretch", "Mat", "Supine Abdominals",
             "foundation", 3, "N/A", 3.0,
             ["Curl up, knees to chest", "Extend arms overhead and legs long",
              "Circle arms back, hug knees in"],
             ["Core", "Full Body"], level="intermediate"),
    Exercise("mat_single_straight_leg", "Single Straight Leg Stretch", "Mat", "Supine Abdominals",
             "foundation", 3, "N/A", 3.0,
             ["Curl up, one leg to ceiling", "Scissor legs, pulling top leg toward you",
              "Keep both legs as straight as possible"],
             ["Core", "Flexibility"], level="intermediate"),
    Exercise("mat_double_straight_leg", "Double Straight Leg Lower/Lift", "Mat", "Supine Abdominals",
             "foundation", 4, "N/A", 3.0,
             ["Hands behind head, legs to ceiling", "Lower both legs as far as back stays down",
              "Exhale to lift legs back up"],
             ["Core", "Full Body"], level="intermediate"),
    Exercise("mat_criss_cross", "Criss Cross", "Mat", "Supine Abdominals",
             "foundation", 3, "N/A", 3.0,
             ["Hands behind head, curl up", "Rotate elbow toward opposite knee",
              "Extend the other leg long, hold the rotation"],
             ["Core", "Full Body"], level="intermediate"),
    Exercise("mat_spine_stretch", "Spine Stretch Forward", "Mat", "Seated Flexion",
             "foundation", 2, "N/A", 3.0,
             ["Sit tall, legs apart, arms forward", "Round over like diving over a ball",
              "Stack back up to tall sitting"],
             ["Flexibility", "Core"], level="intermediate"),
    Exercise("mat_open_leg_rocker", "Open Leg Rocker", "Mat", "Seated Balance",
             "foundation", 3, "N/A", 3.0,
             ["Balance on sit bones, hold ankles, legs in V",
              "Roll back to shoulder blades",
              "Roll back up to balance — don't let go"],
             ["Core", "Balance", "Flexibility"], level="intermediate"),
    Exercise("mat_saw", "Saw", "Mat", "Seated Rotation",
             "foundation", 2, "N/A", 3.0,
             ["Sit tall, legs apart, arms wide", "Rotate and reach pinky to outside of opposite foot",
              "Exhale and pulse deeper, then sit tall"],
             ["Flexibility", "Core"], level="intermediate"),
    Exercise("mat_baby_swan", "Baby Swan", "Mat", "Prone Back Extension",
             "foundation", 2, "N/A", 3.0,
             ["Lie prone, hands under shoulders", "Lift head and chest gently",
              "Keep pubic bone anchored, length through crown"],
             ["Upper Body", "Flexibility"], level="beginner"),
    Exercise("mat_swimming_prep", "Swimming Prep", "Mat", "Prone Back Extension",
             "foundation", 2, "N/A", 3.0,
             ["Lie prone, arms extended forward", "Lift right arm and left leg",
              "Alternate sides with control"],
             ["Core", "Balance", "Upper Body"], level="beginner"),
    Exercise("mat_side_kicks_front_back", "Side Kicks – Front / Back", "Mat", "Side-Lying Hip Work",
             "foundation", 2, "N/A", 3.0,
             ["Side-lying, bottom arm extended, head on arm",
              "Swing top leg front (double pulse) then back",
              "Keep torso absolutely still"],
             ["Lower Body", "Core"], level="beginner"),
    Exercise("mat_side_kicks_up_down", "Side Kicks – Up / Down", "Mat", "Side-Lying Hip Work",
             "foundation", 2, "N/A", 2.0,
             ["Side-lying, kick top leg to ceiling", "Lower slowly with resistance",
              "Inner thigh on the way down"],
             ["Lower Body", "Core"], level="beginner"),
    Exercise("mat_side_kicks_circles", "Side Kicks – Circles", "Mat", "Side-Lying Hip Work",
             "foundation", 2, "N/A", 2.0,
             ["Side-lying, small circles with top leg",
              "Circle in both directions",
              "Keep circles controlled and precise"],
             ["Lower Body", "Core"], level="beginner"),
    Exercise("mat_clams", "Clams", "Mat", "Side-Lying Hip Work",
             "foundation", 1, "N/A", 2.0,
             ["Side-lying, knees bent, feet together", "Open top knee like a clam",
              "Keep feet together, don't rock pelvis"],
             ["Lower Body", "Core"], level="beginner"),
    Exercise("mat_single_leg_kicks", "Single Leg Kicks", "Mat", "Prone Back Extension",
             "foundation", 2, "N/A", 3.0,
             ["Lie prone on forearms, legs extended", "Bend one knee, double pulse heel to seat",
              "Switch legs — keep hips pressing into mat"],
             ["Lower Body", "Core"], level="intermediate"),
    Exercise("mat_mermaid", "Mermaid", "Mat", "Lateral Flexion",
             "foundation", 2, "N/A", 3.0,
             ["Sit with legs folded to one side", "Reach arm overhead into side bend",
              "Create maximum length on the stretching side"],
             ["Flexibility", "Core"], level="intermediate"),
    Exercise("mat_side_balance", "Side Balance / Side Plank Prep", "Mat", "Lateral Flexion",
             "foundation", 3, "N/A", 3.0,
             ["Sit on one hip, legs stacked", "Press up to side plank on hand or forearm",
              "Hold, breathe, lower with control"],
             ["Core", "Upper Body", "Balance"], level="beginner"),
    Exercise("mat_dart", "Dart", "Mat", "Prone Back Extension",
             "foundation", 2, "N/A", 2.0,
             ["Lie prone, arms by sides, palms up", "Lift head, chest, and arms",
              "Reach fingertips toward feet, shoulder blades slide down"],
             ["Upper Body", "Core"], level="beginner"),

    # --- Mat: Peak (14) ---
    Exercise("mat_swan", "Swan / Swan Dive Prep", "Mat", "Prone Back Extension",
             "peak", 4, "N/A", 3.0,
             ["Lie prone, hands under shoulders", "Press up to full extension",
              "Rock forward and back in swan dive"],
             ["Upper Body", "Flexibility", "Core"], level="intermediate"),
    Exercise("mat_swimming", "Swimming", "Mat", "Prone Back Extension",
             "peak", 4, "N/A", 3.0,
             ["Lie prone, lift all four limbs", "Flutter arms and legs quickly",
              "Inhale 5 counts, exhale 5 counts"],
             ["Core", "Full Body"], level="intermediate"),
    Exercise("mat_teaser", "Teaser", "Mat", "Supine Abdominals",
             "peak", 4, "N/A", 3.0,
             ["Lie flat, legs at 45 degrees", "Roll up to V-sit, arms parallel to legs",
              "Balance, then roll down with control"],
             ["Core", "Balance"], level="advanced"),
    Exercise("mat_leg_pull_front", "Leg Pull Front / Front Support", "Mat", "Plank / Full Body",
             "peak", 4, "N/A", 3.0,
             ["Plank position, hands under shoulders", "Lift one leg, point toe",
              "Rock back on heels, shift forward — alternate legs"],
             ["Core", "Upper Body", "Full Body"], level="intermediate"),
    Exercise("mat_leg_pull_back", "Leg Pull Up / Back Support", "Mat", "Plank / Full Body",
             "peak", 4, "N/A", 3.0,
             ["Reverse plank, hands behind, fingers forward",
              "Lift hips high, kick one leg to ceiling",
              "Alternate legs, keep hips lifted"],
             ["Core", "Upper Body", "Full Body"], level="advanced"),
    Exercise("mat_side_plank", "Side Plank / Side Bend", "Mat", "Lateral Flexion",
             "peak", 4, "N/A", 3.0,
             ["Side plank on hand, feet stacked", "Lift hips high in rainbow arc",
              "Lower hip toward floor, lift again"],
             ["Core", "Upper Body", "Balance"], level="advanced"),
    Exercise("mat_kneeling_side_kick", "Kneeling Side Kick", "Mat", "Kneeling Core",
             "peak", 3, "N/A", 3.0,
             ["Kneel, tip to one side, hand on floor", "Extend top leg to hip height",
              "Swing leg front and back maintaining balance"],
             ["Core", "Lower Body", "Balance"], level="intermediate"),
    Exercise("mat_double_leg_kicks", "Double Leg Kicks", "Mat", "Prone Back Extension",
             "peak", 3, "N/A", 3.0,
             ["Lie prone, hands clasped behind back", "Kick both heels to seat 3 times",
              "Extend legs and lift chest, arms reaching back"],
             ["Core", "Upper Body", "Flexibility"], level="advanced"),
    Exercise("mat_scissors", "Scissors in the Air", "Mat", "Supine Abdominals",
             "peak", 4, "N/A", 3.0,
             ["Roll up to shoulder stand, hands support hips",
              "Split legs in scissor motion",
              "Switch legs with control, keep hips over shoulders"],
             ["Core", "Flexibility"], level="advanced"),
    Exercise("mat_bicycle", "Bicycle in the Air", "Mat", "Supine Abdominals",
             "peak", 4, "N/A", 3.0,
             ["From shoulder stand position", "Pedal legs in bicycle motion",
              "Reach one leg long toward floor, other bends"],
             ["Core", "Flexibility"], level="advanced"),
    Exercise("mat_roll_over", "Roll Over", "Mat", "Supine Abdominals",
             "peak", 4, "N/A", 3.0,
             ["Lie supine, legs to ceiling", "Roll legs overhead past head",
              "Open legs, flex feet, roll down one vertebra at a time"],
             ["Core", "Flexibility"], level="advanced"),
    Exercise("mat_neck_pull", "Neck Pull", "Mat", "Supine Abdominals",
             "peak", 4, "N/A", 3.0,
             ["Lie supine, hands behind head", "Curl up and over legs",
              "Round down with control — harder than Roll Up"],
             ["Core", "Flexibility"], level="advanced"),
    Exercise("mat_push_up_flow", "Push-Up Flow", "Mat", "Plank / Full Body",
             "peak", 4, "N/A", 3.0,
             ["Stand tall, walk hands down to plank",
              "Perform 3-5 push-ups",
              "Walk hands back up to standing"],
             ["Upper Body", "Core", "Full Body"], level="intermediate"),
    Exercise("mat_corkscrew", "Corkscrew", "Mat", "Supine Abdominals",
             "peak", 4, "N/A", 3.0,
             ["Lie supine, legs to ceiling", "Circle legs to one side, down, around, and up",
              "Reverse direction — keep shoulders and hips grounded"],
             ["Core", "Flexibility"], level="advanced"),

    # --- Mat: Cooldown (8) ---
    Exercise("mat_seal", "Seal", "Mat", "Seated Flexion",
             "cooldown", 1, "N/A", 3.0,
             ["Balance on sit bones, hold feet from inside",
              "Clap feet 3 times, roll back",
              "Clap 3 times on shoulder blades, roll up to balance"],
             ["Core", "Flexibility"], level="intermediate"),
    Exercise("mat_spine_twist", "Spine Twist", "Mat", "Seated Rotation",
             "cooldown", 2, "N/A", 3.0,
             ["Sit tall, legs together, arms wide", "Rotate torso to one side, double pulse",
              "Return to center, rotate to other side"],
             ["Flexibility", "Core"], level="intermediate"),
    Exercise("mat_child_pose", "Rest Position / Child's Pose", "Mat", "Kneeling Stretch",
             "cooldown", 1, "N/A", 2.0,
             ["Kneel, sit back on heels", "Round forward, arms extended or by sides",
              "Breathe into lower back"],
             ["Flexibility", "Full Body"], level="beginner"),
    Exercise("mat_standing_roll_down", "Standing Roll Down", "Mat", "Standing",
             "cooldown", 1, "N/A", 2.0,
             ["Stand tall, chin to chest", "Roll down one vertebra at a time",
              "Hang at bottom, slowly rebuild to standing"],
             ["Flexibility", "Core"], level="beginner"),
    Exercise("mat_supine_twist_stretch", "Supine Twist / Spinal Rotation", "Mat", "Supine Stretch",
             "cooldown", 1, "N/A", 3.0,
             ["Lie supine, arms out in T", "Drop both knees to one side",
              "Hold and breathe, switch sides"],
             ["Flexibility", "Core"], level="beginner"),
    Exercise("mat_figure_four_stretch", "Figure Four Stretch", "Mat", "Supine Stretch",
             "cooldown", 1, "N/A", 2.0,
             ["Lie supine, cross one ankle over opposite knee",
              "Pull bottom leg toward chest",
              "Deep hip and glute stretch — breathe"],
             ["Flexibility", "Lower Body"], level="beginner"),
    Exercise("mat_calf_stretch", "Calf Stretch", "Mat", "Standing",
             "cooldown", 1, "N/A", 2.0,
             ["Step one foot back, press heel down",
              "Lean forward for gastrocnemius stretch",
              "Bend back knee for soleus stretch"],
             ["Flexibility", "Lower Body"], level="beginner"),
    Exercise("mat_standing_balance", "Standing Balance / One Leg", "Mat", "Standing",
             "cooldown", 1, "N/A", 2.0,
             ["Stand on one leg, other knee lifted",
              "Hold for 30 seconds",
              "Focus gaze on a still point"],
             ["Balance", "Core"], level="beginner"),

    # ═══════════════════════════════════════════════════════════════
    #  CHAIR (Wunda/Combo) — ~22 exercises
    # ═══════════════════════════════════════════════════════════════

    # --- Chair: Warmup (5) ---
    Exercise("chair_footwork_double", "Footwork – Double Leg Press", "Chair", "Footwork",
             "warmup", 2, "1 Heavy + 1 Medium", 3.0,
             ["Sit tall on chair, balls of feet on pedal",
              "Press pedal down with both feet",
              "Resist on the way up — don't let pedal fly"],
             ["Lower Body", "Core"], level="beginner"),
    Exercise("chair_footwork_single", "Footwork – Single Leg", "Chair", "Footwork",
             "warmup", 3, "1 Heavy", 3.0,
             ["One foot on pedal, other on floor or lifted",
              "Press down and resist up with one leg",
              "Keep hips level"],
             ["Lower Body", "Balance", "Core"], level="intermediate"),
    Exercise("chair_seated_triceps", "Seated Triceps Press", "Chair", "Seated Arm Work",
             "warmup", 2, "1 Medium", 3.0,
             ["Sit on chair, hands on front edge of seat",
              "Slide forward, press pedal down with hands behind",
              "Bend and straighten elbows"],
             ["Upper Body", "Core"], level="beginner"),
    Exercise("chair_standing_ankle", "Standing Ankle Pump", "Chair", "Standing",
             "warmup", 1, "1 Heavy", 2.0,
             ["Stand facing chair, one foot on pedal",
              "Press pedal down with ball of foot",
              "Calf raise action with support from arms"],
             ["Lower Body", "Balance"], level="beginner"),
    Exercise("chair_mermaid", "Mermaid", "Chair", "Lateral Flexion",
             "warmup", 2, "1 Medium", 3.0,
             ["Sit sideways on chair, one hand on pedal",
              "Press pedal down while side bending away",
              "Lift back up with oblique control"],
             ["Flexibility", "Core"], level="beginner"),

    # --- Chair: Foundation (8) ---
    Exercise("chair_hamstring_press_1", "Hamstring Press – Prone", "Chair", "Prone Leg Work",
             "foundation", 3, "1 Medium", 3.0,
             ["Lie prone with hips on chair, hands on floor",
              "Press pedal down with one foot",
              "Feel hamstring and glute engage"],
             ["Lower Body", "Core"], level="beginner"),
    Exercise("chair_hamstring_press_2", "Hamstring Press – Kneeling", "Chair", "Kneeling Leg Work",
             "foundation", 3, "1 Medium", 3.0,
             ["Kneel on chair, one foot presses pedal behind",
              "Press pedal down with hamstring",
              "Keep hips square, core engaged"],
             ["Lower Body", "Core"], level="intermediate"),
    Exercise("chair_standing_leg_pump", "Standing Leg Pump", "Chair", "Standing",
             "foundation", 3, "1 Heavy", 3.0,
             ["Stand facing chair, one foot on pedal",
              "Press pedal to floor in standing position",
              "Maintain upright torso, level hips"],
             ["Lower Body", "Balance", "Core"], level="beginner"),
    Exercise("chair_side_balance", "Side Balance", "Chair", "Lateral Flexion",
             "foundation", 2, "1 Light", 3.0,
             ["Sit on chair facing side, legs off edge",
              "Side bend reaching toward floor",
              "Lift back up using lateral waist muscles"],
             ["Core", "Flexibility"], level="beginner"),
    Exercise("chair_cat", "Cat / Spinal Flexion", "Chair", "Kneeling Core",
             "foundation", 2, "1 Medium", 3.0,
             ["Hands on pedal, kneeling in front of chair",
              "Press pedal down while rounding spine",
              "Control pedal back up, articulating spine"],
             ["Core", "Flexibility"], level="intermediate"),
    Exercise("chair_swan_floor", "Swan From Floor", "Chair", "Prone Back Extension",
             "foundation", 3, "1 Medium + 1 Light", 3.0,
             ["Lie prone in front of chair, hands on pedal",
              "Press pedal down while lifting chest",
              "Control the lift with back extensors"],
             ["Upper Body", "Core", "Flexibility"], level="intermediate"),
    Exercise("chair_prone_scap", "Prone Scapular Series", "Chair", "Prone Arm Work",
             "foundation", 3, "1 Medium", 3.0,
             ["Lie prone on chair, hands on pedal below",
              "Press pedal with straight arms — scapular depression",
              "Release up with control"],
             ["Upper Body", "Core"], level="intermediate"),
    Exercise("chair_frogs_facing_out", "Frogs Facing Out", "Chair", "Standing",
             "foundation", 3, "1 Heavy", 3.0,
             ["Stand facing away from chair, heels on pedal in V",
              "Plie to press pedal, stand to let it rise",
              "Focus on pelvic floor and inner thighs"],
             ["Lower Body", "Core"], level="intermediate"),

    # --- Chair: Peak (5) ---
    Exercise("chair_teaser_floor", "Teaser From Floor", "Chair", "Supine Abdominals",
             "peak", 4, "1 Medium", 3.0,
             ["Lie supine in front of chair, feet on pedal",
              "Roll up to V-sit while pressing pedal down",
              "Roll back down with control"],
             ["Core", "Balance"], level="intermediate"),
    Exercise("chair_swan_top", "Swan On Top", "Chair", "Prone Back Extension",
             "peak", 4, "1 Medium", 3.0,
             ["Lie prone on top of chair seat", "Hands on pedal",
              "Press pedal while extending spine into full swan"],
             ["Upper Body", "Flexibility", "Core"], level="intermediate"),
    Exercise("chair_reverse_swan_teaser", "Reverse Swan + Teaser", "Chair", "Full Body",
             "peak", 4, "1 Light", 4.0,
             ["Sit on chair, feet on pedal behind",
              "Press pedal with feet while lying back into extension",
              "Roll back up to seated"],
             ["Core", "Flexibility", "Full Body"], level="advanced"),
    Exercise("chair_press_up_handles", "Press Up With Handles", "Chair", "Standing Arm Work",
             "peak", 4, "1 Heavy", 3.0,
             ["Stand behind chair, hands on handles",
              "Press handles down using triceps and lats",
              "Slowly release — control the negative"],
             ["Upper Body", "Core"], level="intermediate"),
    Exercise("chair_tendon_stretch", "Tendon Stretch", "Chair", "Standing Core",
             "peak", 5, "1 Medium + 1 Light", 3.0,
             ["Stand on chair seat, hands on front edge",
              "Round over, press pedal down with feet",
              "Pull pedal up with deep abdominal scoop"],
             ["Core", "Full Body"], level="advanced"),

    # --- Chair: Cooldown (4) ---
    Exercise("chair_side_pull_up", "Side Pull Up", "Chair", "Lateral Flexion",
             "cooldown", 2, "1 Light", 3.0,
             ["Stand beside chair, inside foot on pedal",
              "Press down then slowly control up",
              "Focus on lateral waist engagement"],
             ["Core", "Balance"], level="intermediate"),
    Exercise("chair_forward_lunge", "Forward Lunge", "Chair", "Standing Stretch",
             "cooldown", 2, "1 Medium", 3.0,
             ["Step one foot on pedal behind chair",
              "Lunge forward, pedal goes down",
              "Deep hip flexor and quad stretch"],
             ["Flexibility", "Lower Body", "Balance"], level="advanced"),
    Exercise("chair_side_lunge", "Side Lunge", "Chair", "Standing Stretch",
             "cooldown", 2, "1 Medium", 3.0,
             ["Stand beside chair, one foot on pedal",
              "Lunge to the side, pressing pedal down",
              "Inner thigh stretch and strengthening"],
             ["Flexibility", "Lower Body"], level="advanced"),
    Exercise("chair_piano_lesson", "Piano Lesson", "Chair", "Footwork",
             "cooldown", 3, "1 Light each side", 3.0,
             ["Sit on chair, feet on split pedal",
              "Alternate pressing left and right pedal",
              "Like playing piano with your feet"],
             ["Lower Body", "Core", "Balance"], level="advanced"),

    # ═══════════════════════════════════════════════════════════════
    #  CADILLAC / TOWER — ~28 exercises
    # ═══════════════════════════════════════════════════════════════

    # --- Cadillac: Warmup (7) ---
    Exercise("cad_breathing", "Breathing / 90-90 Arms", "Cadillac", "Supine Arm Work",
             "warmup", 1, "2 Arm Springs", 3.0,
             ["Lie supine, hold push-through bar or arm springs",
              "Press bar up on exhale, resist down on inhale",
              "Focus on rib cage expansion"],
             ["Upper Body", "Core", "Flexibility"], level="beginner"),
    Exercise("cad_supine_scap", "Supine Scapular Series", "Cadillac", "Supine Arm Work",
             "warmup", 2, "2 Arm Springs", 3.0,
             ["Lie supine, hold arm springs", "Protract and retract shoulder blades",
              "Then add elevation and depression"],
             ["Upper Body", "Core"], level="beginner"),
    Exercise("cad_footwork", "Footwork", "Cadillac", "Supine Leg Work",
             "warmup", 1, "2 Leg Springs", 3.0,
             ["Lie supine, feet in leg spring loops",
              "Press legs out in parallel, V, and wide positions",
              "Similar to Reformer footwork with spring resistance"],
             ["Lower Body", "Core"], level="beginner"),
    Exercise("cad_supine_leg_springs", "Supine Leg Springs", "Cadillac", "Supine Leg Work",
             "warmup", 2, "2 Leg Springs", 3.0,
             ["Legs in spring loops, circles and scissors",
              "Walking motion forward and back",
              "Keep pelvis stable throughout"],
             ["Lower Body", "Core", "Flexibility"], level="beginner"),
    Exercise("cad_roll_down", "Roll Down Bar", "Cadillac", "Seated Flexion",
             "warmup", 2, "Push-Through Bar (bottom)", 3.0,
             ["Sit facing push-through bar, hold bar",
              "Roll down through spine with bar assisting",
              "Roll back up using abdominals"],
             ["Core", "Flexibility"], level="beginner"),
    Exercise("cad_seated_push_through", "Seated Push-Through", "Cadillac", "Seated Flexion",
             "warmup", 2, "Push-Through Bar (top)", 3.0,
             ["Sit facing tower, push bar forward and overhead",
              "Round forward over legs with bar",
              "Articulate back up to seated"],
             ["Flexibility", "Core"], level="beginner"),
    Exercise("cad_standing_leg_springs", "Standing Leg Springs", "Cadillac", "Standing Leg Work",
             "warmup", 2, "1 Leg Spring", 3.0,
             ["Stand facing tower, one ankle in spring",
              "Press leg back against spring resistance",
              "Forward, side, and back variations"],
             ["Lower Body", "Balance"], level="beginner"),

    # --- Cadillac: Foundation (10) ---
    Exercise("cad_tower", "Tower / Shoulder Bridge", "Cadillac", "Supine Leg Work",
             "foundation", 3, "2 Leg Springs + Push Bar", 4.0,
             ["Lie supine, feet on push-through bar",
              "Roll hips up, press bar to ceiling",
              "Roll down one vertebra at a time"],
             ["Core", "Lower Body", "Flexibility"], level="intermediate"),
    Exercise("cad_monkey", "Monkey", "Cadillac", "Supine Leg Work",
             "foundation", 3, "2 Leg Springs + Push Bar", 3.0,
             ["Lie supine, feet on bar",
              "Press bar up while keeping hips grounded",
              "Like footwork but with the push-through bar"],
             ["Lower Body", "Core"], level="intermediate"),
    Exercise("cad_parakeet", "Parakeet", "Cadillac", "Supine Leg Work",
             "foundation", 3, "Push-Through Bar (bottom)", 3.0,
             ["Lie supine, feet on push-through bar",
              "Roll hips up into bridge, extend knees",
              "Bend knees, then roll down"],
             ["Core", "Lower Body"], level="intermediate"),
    Exercise("cad_teaser", "Teaser", "Cadillac", "Supine Abdominals",
             "foundation", 3, "2 Arm Springs", 3.0,
             ["Lie supine holding arm springs",
              "Roll up to V-sit with spring assistance",
              "Roll down with control"],
             ["Core", "Balance"], level="beginner"),
    Exercise("cad_pelvic_press", "Pelvic Press", "Cadillac", "Supine Leg Work",
             "foundation", 3, "Fuzzy Loops + Push Bar", 3.0,
             ["Lie supine, feet in fuzzy loops",
              "Lift hips to bridge and press feet overhead",
              "Roll down with legs assisting"],
             ["Core", "Lower Body", "Flexibility"], level="intermediate"),
    Exercise("cad_side_lying_springs", "Side-Lying Leg Springs", "Cadillac", "Side-Lying Hip Work",
             "foundation", 2, "1 Leg Spring", 3.0,
             ["Side-lying on table, top ankle in spring",
              "Lift and lower top leg against spring",
              "Circles, front/back, up/down variations"],
             ["Lower Body", "Core"], level="beginner"),
    Exercise("cad_prone_arm_springs", "Prone Arm Springs", "Cadillac", "Prone Arm Work",
             "foundation", 2, "2 Arm Springs", 3.0,
             ["Lie prone, hold arm springs",
              "Pull arms alongside body, lift chest slightly",
              "Release with control"],
             ["Upper Body", "Core"], level="beginner"),
    Exercise("cad_seated_pull_down", "Seated Pull Down", "Cadillac", "Seated Arm Work",
             "foundation", 3, "Push-Through Bar (top)", 3.0,
             ["Sit cross-legged, reach up to push-through bar",
              "Pull bar down to chest level",
              "Like a lat pull-down with spinal engagement"],
             ["Upper Body", "Core"], level="beginner"),
    Exercise("cad_hip_extension", "Hip Extension", "Cadillac", "Supine Leg Work",
             "foundation", 3, "Fuzzy Loops", 3.0,
             ["Lie prone, ankles in fuzzy loops",
              "Press legs back and up against springs",
              "Squeeze glutes, keep pelvis on table"],
             ["Lower Body", "Core"], level="intermediate"),
    Exercise("cad_standing_arm_springs_in", "Standing Arm Springs – Facing In", "Cadillac", "Standing Arm Work",
             "foundation", 3, "2 Arm Springs", 3.0,
             ["Stand facing tower, hold arm springs overhead",
              "Pull springs down to sides in arc",
              "Control return — chest expansion motion"],
             ["Upper Body", "Core"], level="intermediate"),

    # --- Cadillac: Peak (6) ---
    Exercise("cad_hip_opener", "Hip Opener", "Cadillac", "Supine Leg Work",
             "peak", 3, "Fuzzy Loops", 3.0,
             ["Lie supine, feet in fuzzy loops",
              "Open legs wide against spring resistance",
              "Close with inner thigh control"],
             ["Lower Body", "Flexibility"], level="intermediate"),
    Exercise("cad_spread_eagle", "Spread Eagle", "Cadillac", "Full Body",
             "peak", 4, "Arm + Leg Springs", 4.0,
             ["Lie supine, hold arm springs, feet in leg springs",
              "Simultaneously extend all four limbs out",
              "Return to center with coordination"],
             ["Full Body", "Core", "Flexibility"], level="intermediate"),
    Exercise("cad_hanging", "Hanging / Pull Up", "Cadillac", "Standing Arm Work",
             "peak", 4, "Trapeze Bar", 3.0,
             ["Hold overhead trapeze bar",
              "Bend knees and hang, then pull up",
              "Decompress spine while building upper body strength"],
             ["Upper Body", "Core", "Flexibility"], level="intermediate"),
    Exercise("cad_magician", "Magician", "Cadillac", "Full Body",
             "peak", 5, "Push-Through Bar (bottom)", 4.0,
             ["Stand on table, hold push-through bar",
              "Roll down through spine, bar moves with you",
              "Advanced full-body articulation and control"],
             ["Core", "Flexibility", "Full Body"], level="advanced"),
    Exercise("cad_dolphin", "Dolphin", "Cadillac", "Prone Back Extension",
             "peak", 4, "Push-Through Bar (bottom)", 3.0,
             ["Lie prone, hold push-through bar",
              "Press bar forward and down while lifting chest",
              "Undulating wave-like motion through spine"],
             ["Upper Body", "Core", "Flexibility"], level="advanced"),
    Exercise("cad_swan", "Swan on Cadillac", "Cadillac", "Prone Back Extension",
             "peak", 4, "Push-Through Bar (top)", 3.0,
             ["Lie prone, arms extended holding bar",
              "Push bar up while extending spine fully",
              "Control the return with core engagement"],
             ["Upper Body", "Flexibility", "Core"], level="advanced"),

    # --- Cadillac: Cooldown (5) ---
    Exercise("cad_circumduction", "Circumduction", "Cadillac", "Supine Arm Work",
             "cooldown", 1, "2 Arm Springs", 3.0,
             ["Lie supine, hold arm springs",
              "Large arm circles overhead and around",
              "Open chest and shoulders"],
             ["Flexibility", "Upper Body"], level="beginner"),
    Exercise("cad_thigh_stretch", "Thigh Stretch", "Cadillac", "Kneeling Stretch",
             "cooldown", 2, "Push-Through Bar or Springs", 3.0,
             ["Kneel on table, hold push-through bar or springs",
              "Lean back from knees, straight line from knee to head",
              "Return to upright using quads"],
             ["Flexibility", "Lower Body", "Core"], level="beginner"),
    Exercise("cad_squats", "Standing Squats", "Cadillac", "Standing Leg Work",
             "cooldown", 2, "Push-Through Bar or Arm Springs", 3.0,
             ["Stand on table, hold bar for support",
              "Squat down with control",
              "Bar assists balance and alignment"],
             ["Lower Body", "Balance"], level="intermediate"),
    Exercise("cad_standing_arm_springs_out", "Standing Arm Springs – Facing Out", "Cadillac", "Standing Arm Work",
             "cooldown", 2, "2 Arm Springs", 3.0,
             ["Stand facing away from tower",
              "Press arms forward and return",
              "Chest expansion and shoulder opening"],
             ["Upper Body", "Flexibility"], level="intermediate"),
    Exercise("cad_semi_circle", "Semi-Circle", "Cadillac", "Supine Hip Work",
             "cooldown", 2, "Push-Through Bar (bottom)", 3.0,
             ["Lie supine, feet on push-through bar",
              "Roll hips up, press bar away, drop hips, pull bar in",
              "Reverse direction — mobilizes entire spine"],
             ["Flexibility", "Core", "Lower Body"], level="advanced"),

    # ═══════════════════════════════════════════════════════════════
    #  LADDER BARREL — ~15 exercises
    # ═══════════════════════════════════════════════════════════════

    # --- Ladder Barrel: Warmup (4) ---
    Exercise("lb_leg_stretches", "Leg Stretches", "Ladder Barrel", "Standing Stretch",
             "warmup", 1, "N/A", 3.0,
             ["Stand facing barrel, place one foot on rung",
              "Stretch forward over leg, hamstring focus",
              "Side stretch and rotating stretch variations"],
             ["Flexibility", "Lower Body"], level="beginner"),
    Exercise("lb_horseback", "Horseback / Seated Stretch", "Ladder Barrel", "Seated Stretch",
             "warmup", 1, "N/A", 3.0,
             ["Sit on barrel facing ladder, straddle",
              "Round forward over barrel, stretching back",
              "Side bending and rotation variations"],
             ["Flexibility", "Core"], level="beginner"),
    Exercise("lb_standing_back_bend", "Standing Back Bend", "Ladder Barrel", "Standing Back Extension",
             "warmup", 2, "N/A", 3.0,
             ["Stand with back to barrel, hands on rungs",
              "Lean back over barrel into supported extension",
              "Use arms and legs for control"],
             ["Flexibility", "Upper Body"], level="beginner"),
    Exercise("lb_dart", "Dart / Prone Extension", "Ladder Barrel", "Prone Back Extension",
             "warmup", 2, "N/A", 3.0,
             ["Lie prone over barrel, hips at apex",
              "Lift chest into gentle extension",
              "Arms by sides or reaching forward"],
             ["Upper Body", "Core"], level="beginner"),

    # --- Ladder Barrel: Foundation (5) ---
    Exercise("lb_short_box", "Short Box Series", "Ladder Barrel", "Seated Flexion",
             "foundation", 3, "N/A", 4.0,
             ["Sit on barrel, feet hooked under rung",
              "Round back, flat back, side bend, twist",
              "Greater range of motion than Reformer box"],
             ["Core", "Flexibility"], level="intermediate"),
    Exercise("lb_side_over", "Side Over", "Ladder Barrel", "Lateral Flexion",
             "foundation", 3, "N/A", 3.0,
             ["Lie sideways over barrel, feet under rung",
              "Lower torso over barrel, then lift up",
              "Intense lateral waist strengthening"],
             ["Core", "Flexibility"], level="intermediate"),
    Exercise("lb_side_sit_up_basic", "Side Sit-Up – Basic", "Ladder Barrel", "Lateral Flexion",
             "foundation", 2, "N/A", 3.0,
             ["Sit on barrel, feet anchored on rungs",
              "Lower sideways toward floor",
              "Lift back up using obliques"],
             ["Core", "Flexibility"], level="beginner"),
    Exercise("lb_swimming_grasshopper", "Swimming / Grasshopper", "Ladder Barrel", "Prone Back Extension",
             "foundation", 3, "N/A", 3.0,
             ["Lie prone over barrel",
              "Swimming: flutter arms and legs",
              "Grasshopper: clap heels together, then open"],
             ["Core", "Upper Body", "Lower Body"], level="intermediate"),
    Exercise("lb_swan", "Swan", "Ladder Barrel", "Prone Back Extension",
             "foundation", 3, "N/A", 3.0,
             ["Lie prone over barrel, hands on rungs",
              "Pull body up into full extension",
              "Barrel supports the curve of the spine"],
             ["Upper Body", "Flexibility", "Core"], level="intermediate"),

    # --- Ladder Barrel: Peak (3) ---
    Exercise("lb_swan_dive", "Swan Dive", "Ladder Barrel", "Prone Back Extension",
             "peak", 4, "N/A", 3.0,
             ["From full swan position on barrel",
              "Release hands and rock forward and back",
              "Arms reach forward as torso tips"],
             ["Upper Body", "Core", "Full Body"], level="advanced"),
    Exercise("lb_side_sit_up_adv", "Side Sit-Up – Advanced", "Ladder Barrel", "Lateral Flexion",
             "peak", 4, "N/A", 3.0,
             ["Full range side sit-up over barrel",
              "Top arm reaches overhead for added challenge",
              "Slow, controlled movement throughout"],
             ["Core", "Flexibility"], level="advanced"),
    Exercise("lb_roll_over_shoulder", "Roll Over / Shoulder Stand", "Ladder Barrel", "Supine Inversion",
             "peak", 4, "N/A", 3.0,
             ["Lie supine on barrel, hands on rungs",
              "Roll legs overhead into shoulder stand",
              "Barrel supports and deepens the stretch"],
             ["Core", "Flexibility"], level="advanced"),

    # --- Ladder Barrel: Cooldown (3) ---
    Exercise("lb_semi_circle", "Semi-Circle / Bridging", "Ladder Barrel", "Supine Hip Work",
             "cooldown", 2, "N/A", 3.0,
             ["Lie supine over barrel, feet on rung",
              "Roll hips up and down over barrel",
              "Spinal massage effect"],
             ["Flexibility", "Core", "Lower Body"], level="intermediate"),
    Exercise("lb_side_dangling", "Side Dangling", "Ladder Barrel", "Lateral Flexion",
             "cooldown", 1, "N/A", 3.0,
             ["Sit sideways on barrel, drape over side",
              "Let gravity open the side body",
              "Passive stretch — just breathe"],
             ["Flexibility", "Core"], level="intermediate"),
    Exercise("lb_leg_series", "Leg Series / Stretches", "Ladder Barrel", "Supine Stretch",
             "cooldown", 1, "N/A", 3.0,
             ["Lie supine on barrel, leg stretches in various directions",
              "Hamstring, hip flexor, IT band",
              "Barrel provides feedback and support"],
             ["Flexibility", "Lower Body"], level="advanced"),

    # ═══════════════════════════════════════════════════════════════
    #  SPINE CORRECTOR — ~16 exercises
    # ═══════════════════════════════════════════════════════════════

    # --- Spine Corrector: Warmup (4) ---
    Exercise("sc_bridging", "Bridging", "Spine Corrector", "Supine Hip Work",
             "warmup", 2, "N/A", 3.0,
             ["Lie supine over arc, feet on floor",
              "Peel hips up into bridge",
              "Arc supports thoracic extension"],
             ["Core", "Lower Body"], level="beginner"),
    Exercise("sc_chest_lift", "Chest Lift", "Spine Corrector", "Supine Abdominals",
             "warmup", 2, "N/A", 3.0,
             ["Lie back over arc, hands behind head",
              "Curl up using abdominals",
              "Greater range of motion than on flat mat"],
             ["Core", "Full Body"], level="beginner"),
    Exercise("sc_hundred", "Hundred", "Spine Corrector", "Supine Abdominals",
             "warmup", 3, "N/A", 4.0,
             ["Lie back over arc, classic hundred position",
              "Pump arms, arc adds range for deeper scoop",
              "Inhale 5, exhale 5"],
             ["Core", "Full Body"], level="beginner"),
    Exercise("sc_roll_down", "Roll Down", "Spine Corrector", "Seated Flexion",
             "warmup", 2, "N/A", 3.0,
             ["Sit on lip of arc facing away",
              "Roll down over the arc one vertebra at a time",
              "Arc guides and supports spinal articulation"],
             ["Core", "Flexibility"], level="beginner"),

    # --- Spine Corrector: Foundation (5) ---
    Exercise("sc_stomach_series", "Stomach Series", "Spine Corrector", "Supine Abdominals",
             "foundation", 3, "N/A", 5.0,
             ["Single Leg Stretch, Double Leg Stretch on arc",
              "Single Straight, Criss Cross",
              "Arc adds range — more challenging than flat"],
             ["Core", "Full Body"], level="intermediate"),
    Exercise("sc_leg_series", "Leg Series", "Spine Corrector", "Supine Leg Work",
             "foundation", 2, "N/A", 4.0,
             ["Lie back over arc, legs to ceiling",
              "Circles, scissors, lower/lift",
              "Arc supports pelvis for deeper leg work"],
             ["Lower Body", "Core"], level="beginner"),
    Exercise("sc_side_over", "Side Over", "Spine Corrector", "Lateral Flexion",
             "foundation", 3, "N/A", 3.0,
             ["Lie sideways over arc, feet anchored",
              "Lower toward floor, then lift using obliques",
              "Arc supports the waist"],
             ["Core", "Flexibility"], level="intermediate"),
    Exercise("sc_side_kicks", "Side Kicks", "Spine Corrector", "Side-Lying Hip Work",
             "foundation", 2, "N/A", 3.0,
             ["Lie sideways on arc",
              "Kick top leg front and back",
              "Arc challenges stability more than flat mat"],
             ["Lower Body", "Core"], level="beginner"),
    Exercise("sc_mermaid", "Mermaid", "Spine Corrector", "Lateral Flexion",
             "foundation", 2, "N/A", 3.0,
             ["Sit on arc with legs to one side",
              "Side bend over the arc",
              "Deep lateral stretch supported by curve"],
             ["Flexibility", "Core"], level="beginner"),

    # --- Spine Corrector: Peak (4) ---
    Exercise("sc_seated_back_bend", "Seated Back Bend / Reach", "Spine Corrector", "Seated Back Extension",
             "peak", 3, "N/A", 3.0,
             ["Sit on lip, lean back into extension",
              "Arms reach overhead",
              "Thoracic opener over the arc"],
             ["Flexibility", "Upper Body"], level="beginner"),
    Exercise("sc_dart_swimming", "Dart + Swimming", "Spine Corrector", "Prone Back Extension",
             "peak", 3, "N/A", 3.0,
             ["Lie prone over arc, hips at apex",
              "Lift into dart, then add swimming flutter",
              "Arc supports belly while building back strength"],
             ["Core", "Upper Body"], level="intermediate"),
    Exercise("sc_teaser", "Teaser", "Spine Corrector", "Supine Abdominals",
             "peak", 4, "N/A", 3.0,
             ["Lie back over arc",
              "Roll up to V-sit — arc adds challenge",
              "Balance, then roll back with control"],
             ["Core", "Balance"], level="advanced"),
    Exercise("sc_balance_point", "Balance Point", "Spine Corrector", "Seated Balance",
             "peak", 3, "N/A", 3.0,
             ["Sit on arc, find balance on sit bones",
              "Extend legs in V, arms forward",
              "Hold balance — arc makes surface unstable"],
             ["Core", "Balance"], level="intermediate"),

    # --- Spine Corrector: Cooldown (3) ---
    Exercise("sc_corkscrew", "Corkscrew", "Spine Corrector", "Supine Abdominals",
             "cooldown", 2, "N/A", 3.0,
             ["Lie back over arc, legs to ceiling",
              "Circle legs to one side and around",
              "Arc supports pelvis for spinal mobilization"],
             ["Core", "Flexibility"], level="intermediate"),
    Exercise("sc_roll_over", "Roll Over", "Spine Corrector", "Supine Inversion",
             "cooldown", 2, "N/A", 3.0,
             ["Lie back over arc, legs to ceiling",
              "Roll legs overhead past face",
              "Arc assists the rolling motion"],
             ["Flexibility", "Core"], level="beginner"),
    Exercise("sc_back_bend_stretch", "Supported Back Bend Stretch", "Spine Corrector", "Supine Stretch",
             "cooldown", 1, "N/A", 3.0,
             ["Lie supine over arc, arms overhead",
              "Let gravity open the chest and front body",
              "Passive stretch — breathe deeply"],
             ["Flexibility", "Upper Body"], level="beginner"),
]


# ─────────────────────────────────────────────
# Generator Engine
# ─────────────────────────────────────────────

# Phase proportions for the bell-curve class structure
PHASE_RATIOS = {
    "warmup":     0.20,
    "foundation": 0.30,
    "peak":       0.30,
    "cooldown":   0.20,
}

PHASE_ORDER = ["warmup", "foundation", "peak", "cooldown"]

THEMES = ["Core", "Flexibility", "Lower Body", "Upper Body", "Full Body", "Balance"]
APPARATUS_OPTIONS = ["Reformer", "Mat", "Chair", "Cadillac", "Mixed", "Ladder Barrel", "Spine Corrector"]
ENERGY_LEVELS = {
    "Gentle (1-2)": (1, 2),
    "Moderate (2-3)": (2, 3),
    "Challenging (3-4)": (3, 4),
    "Intense (4-5)": (4, 5),
}


def get_exercises_for_apparatus(apparatus: str) -> list[Exercise]:
    """Filter exercises by apparatus. 'Mixed' returns everything."""
    if apparatus == "Mixed":
        return EXERCISE_DB[:]
    return [e for e in EXERCISE_DB if e.apparatus == apparatus]


def generate_workout(
    duration_minutes: int,
    apparatus: str,
    theme: str,
    energy_label: str,
) -> list[dict]:
    """
    Build a workout using the bell-curve class structure.
    Returns a list of exercise dicts with an added 'phase_label' key.
    """
    energy_min, energy_max = ENERGY_LEVELS.get(energy_label, (1, 5))
    pool = get_exercises_for_apparatus(apparatus)

    # Filter by theme (allow exercises that list this theme)
    if theme != "Full Body":
        themed = [e for e in pool if theme in e.themes]
        # Keep at least some from each phase even if theme is narrow
        for phase in PHASE_ORDER:
            phase_themed = [e for e in themed if e.phase == phase]
            if len(phase_themed) < 2:
                # backfill with any exercise from that phase
                extras = [e for e in pool if e.phase == phase and e not in themed]
                themed.extend(extras[:3])
        pool = themed if themed else pool

    # Calculate time budget per phase
    time_budget = {}
    for phase, ratio in PHASE_RATIOS.items():
        time_budget[phase] = duration_minutes * ratio

    workout = []
    used_slugs = set()

    for phase in PHASE_ORDER:
        budget = time_budget[phase]
        candidates = [e for e in pool if e.phase == phase and e.slug not in used_slugs]

        # Soft-filter by energy for foundation/peak phases
        if phase in ("foundation", "peak"):
            energy_filtered = [e for e in candidates if energy_min <= e.energy <= energy_max]
            if len(energy_filtered) >= 2:
                candidates = energy_filtered

        random.shuffle(candidates)
        phase_time = 0.0

        for ex in candidates:
            if phase_time + ex.duration_min <= budget + 1.0:  # allow slight overflow
                entry = ex.to_dict()
                entry["phase_label"] = phase.capitalize()
                workout.append(entry)
                used_slugs.add(ex.slug)
                phase_time += ex.duration_min

    return workout


def smart_swap(workout: list[dict], index: int) -> Optional[dict]:
    """
    Swap exercise at `index` with another from the same category + phase.
    Returns the new exercise dict, or None if no swap is available.
    """
    current = workout[index]
    used_slugs = {e.get("slug", "") for e in workout}

    candidates = [
        e for e in EXERCISE_DB
        if e.category == current.get("category", "")
        and e.phase == current.get("phase", current.get("phase_label", "")).lower()
        and e.slug not in used_slugs
    ]

    # Broaden: same phase, similar energy if category match fails
    if not candidates:
        candidates = [
            e for e in EXERCISE_DB
            if e.phase == current.get("phase", current.get("phase_label", "")).lower()
            and e.apparatus == current.get("apparatus", "")
            and e.slug not in used_slugs
        ]

    # Broadest: same phase, any apparatus
    if not candidates:
        candidates = [
            e for e in EXERCISE_DB
            if e.phase == current.get("phase", current.get("phase_label", "")).lower()
            and e.slug not in used_slugs
        ]

    if not candidates:
        return None

    pick = random.choice(candidates)
    entry = pick.to_dict()
    entry["phase_label"] = current.get("phase_label", pick.phase.capitalize())
    return entry


# ─────────────────────────────────────────────
# Serialization
# ─────────────────────────────────────────────

def workout_to_json(workout: list[dict]) -> str:
    """Serialize a workout for Google Sheets storage."""
    return json.dumps(workout, default=str)


def json_to_workout(json_str: str) -> list[dict]:
    """Deserialize a workout from Google Sheets.

    Handles two formats:
    1. Flat list: [{name, apparatus, ...}, ...]  (app-generated)
    2. Nested dict: {apparatus, exercises: [...]} (imported)
    """
    data = json.loads(json_str)
    if isinstance(data, list):
        return data
    elif isinstance(data, dict) and "exercises" in data:
        # Imported format — flatten and add apparatus to each exercise
        apparatus = data.get("apparatus", "Reformer")
        exercises = data["exercises"]
        for ex in exercises:
            if "apparatus" not in ex or not ex["apparatus"]:
                ex["apparatus"] = apparatus
            # Ensure required display fields have defaults
            if "duration_min" not in ex:
                ex["duration_min"] = 5
            if "phase_label" not in ex:
                ex["phase_label"] = ex.get("phase", "foundation").capitalize()
        return exercises
    else:
        return []
